kube-prometheus-stack:
  
  # 1. Grafana Settings
  admin:
      existingSecret: "grafana-admin-credentials"
      userKey: admin-user
      passwordKey: admin-password
    
    # Expose Grafana to the internet
    ingress:
      enabled: true
      ingressClassName: nginx
      hosts:
        - grafana.teslarez.xyz
        
    # Ask Rancher Local Path for a hard drive to save dashboards
    persistence:
      enabled: true
      type: pvc
      storageClassName: "local-path"
      accessModes:
        - ReadWriteOnce
      size: 2Gi

  # 2. Prometheus Settings
  prometheus:
    prometheusSpec:
      # Ask Rancher Local Path for a hard drive to save historical metrics
      storageSpec:
        volumeClaimTemplate:
          spec:
            storageClassName: "local-path"
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 5Gi
